// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Users.Get.GetUser.Execute(Orquestra.Application.UseCases.Users.Shared.UserInput)~System.Threading.Tasks.Task{System.ValueTuple{Orquestra.Application.UseCases.Users.Shared.UserOutput,System.String}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Companies.Base.CompanyBase.Validate(Orquestra.Application.UseCases.Companies.Shared.CompanyInput,System.Guid,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Clients.Base.ClientBase.Validate(Orquestra.Application.UseCases.Clients.Shared.ClientInput,System.Guid,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Users.Get.GetUser.Execute(System.Nullable{System.Guid},System.String,System.Boolean)~System.Threading.Tasks.Task{Orquestra.Application.UseCases.Users.Shared.UserOutput}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Companies.Base.CompanyBase.Validate(Orquestra.Application.UseCases.Companies.Shared.CompanyInput,System.Guid,System.Boolean,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Companies.Base.CompanyBase.Validate(Orquestra.Application.UseCases.Companies.Shared.CompanyInput,System.Guid,System.Boolean,System.Boolean,System.Boolean)~System.Threading.Tasks.Task")]
