using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Users.Get.GetUser.Execute(Orquestra.Application.UseCases.Users.Shared.UserInput)~System.Threading.Tasks.Task{System.ValueTuple{Orquestra.Application.UseCases.Users.Shared.UserOutput,System.String}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Companies.Base.CompanyBase.Validate(Orquestra.Application.UseCases.Companies.Shared.CompanyInput,System.Guid,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Clients.Base.ClientBase.Validate(Orquestra.Application.UseCases.Clients.Shared.ClientInput,System.Guid,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Users.Get.GetUser.Execute(System.Nullable{System.Guid},System.String,System.Boolean)~System.Threading.Tasks.Task{Orquestra.Application.UseCases.Users.Shared.UserOutput}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Companies.Base.CompanyBase.Validate(Orquestra.Application.UseCases.Companies.Shared.CompanyInput,System.Guid,System.Boolean,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Companies.Base.CompanyBase.Validate(Orquestra.Application.UseCases.Companies.Shared.CompanyInput,System.Guid,System.Boolean,System.Boolean,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Clients.GetAllByCompanyId.GetAllClientByCompanyId.Execute(Orquestra.Application.UseCases.Shared.PaginationInput,Orquestra.Application.UseCases.Clients.Shared.ClientInput,System.Guid,System.Guid)~System.Threading.Tasks.Task{System.ValueTuple{System.Collections.Generic.IEnumerable{Orquestra.Application.UseCases.Clients.Shared.ClientOutput},System.Int32}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.CompanyUsers.Invite.InviteCompanyUser.InviteUserWhoAlreadyHaveAccount(System.Guid,Orquestra.Application.UseCases.Companies.Shared.CompanyOutput,Orquestra.Application.UseCases.Users.Shared.UserOutput,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.CompanyUsers.GetAllByCompanyId.GetAllCompanyUserByCompanyId.Execute(Orquestra.Application.UseCases.Shared.PaginationInput,Orquestra.Application.UseCases.CompanyUsers.Shared.CompanyUserFilterInput,System.Guid,System.Guid)~System.Threading.Tasks.Task{System.ValueTuple{System.Collections.Generic.IEnumerable{Orquestra.Application.UseCases.CompanyUsers.Shared.CompanyUserOutput},System.Int32}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Orquestra.Application.UseCases.Inventories.GetAllByCompanyId.GetAllInventoryByCompanyId.Execute(Orquestra.Application.UseCases.Shared.PaginationInput,System.Guid,System.Guid,Orquestra.Application.UseCases.Inventories.Shared.InventoryInput)~System.Threading.Tasks.Task{System.ValueTuple{System.Collections.Generic.IEnumerable{Orquestra.Domain.Entities.Inventory},System.Int32}}")]